# Generated by Django 5.0.7 on 2024-07-23 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=20)),
                ('activos', models.ManyToManyField(to='portafolio.activo')),
            ],
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateField()),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.portafolio')),
            ],
            options={
                'unique_together': {('portafolio', 'activo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateField()),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.portafolio')),
            ],
            options={
                'unique_together': {('portafolio', 'activo')},
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.activo')),
            ],
            options={
                'unique_together': {('activo', 'fecha')},
            },
        ),
    ]
