# Generated by Django 5.0.7 on 2024-07-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
